LRUK:
  - k: 4
LFO:
  - cutoff: 0.5
    window: 10000000
    sample_size: 1000000
    sample_type: 2
LR:
  - sample_rate: 32
    threshold: 10000000
    batch_size: 10
    learning_rate: 0.000001
    n_past_intervals: 4
